# -*- coding: utf-8 -*-
"""PCD23424014

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKQ1W_dZLD78p9B6BVN7Ha2tdDmlO9MK
"""

# ============================================================
#  IMAGE PROCESSING TOOLKIT — Google Colab / Jupyter
# ============================================================

# CELL 1: Import
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

print("● Library siap!")

# ============================================================
#  FUNGSI UTAMA
# ============================================================

def load_image(path):
    return np.array(Image.open(path).convert('RGB'))

def rgb_to_grayscale(rgb):
    r, g, b = rgb[:,:,0].astype(np.float64), rgb[:,:,1].astype(np.float64), rgb[:,:,2].astype(np.float64)
    return (0.299*r + 0.587*g + 0.114*b).astype(np.uint8)

def grayscale_to_binary(gray, threshold=128):
    return np.where(gray >= threshold, 255, 0).astype(np.uint8)

def grayscale_to_mbit(gray, m=4):
    step = 256 / (2 ** m)
    return (np.floor(gray / step) * step).astype(np.uint8)

def adjust_brightness(gray, value=50):
    return np.clip(gray.astype(np.int32) + value, 0, 255).astype(np.uint8)

def adjust_contrast(gray, factor=1.5):
    mean = np.mean(gray)
    return np.clip(mean + factor * (gray.astype(np.float64) - mean), 0, 255).astype(np.uint8)

def compute_histogram(gray):
    hist, _ = np.histogram(gray.flatten(), bins=256, range=(0, 255))
    return hist

def histogram_equalization(gray):
    hist = compute_histogram(gray)
    cdf = hist.cumsum()
    cdf_min = cdf[cdf > 0].min()
    lut = np.round((cdf - cdf_min) / (gray.size - cdf_min) * 255).astype(np.uint8)
    return lut[gray]

print("● Fungsi siap!")

# ============================================================
#  CELL 2: Upload Gambar
# ============================================================
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

original = load_image(filename)
gray     = rgb_to_grayscale(original)
print(f"● Gambar: {filename} | Ukuran: {original.shape[1]}×{original.shape[0]} px")

# ============================================================
#  CELL 3: Tampilkan Semua Hasil
# ============================================================

# Parameter (ubah sesuai kebutuhan)
THRESHOLD = 128
M_BIT     = 4
BRIGHTNESS = 60
CONTRAST   = 1.8

# Proses semua operasi
binary    = grayscale_to_binary(gray, THRESHOLD)
mbit      = grayscale_to_mbit(gray, M_BIT)
bright    = adjust_brightness(gray, BRIGHTNESS)
cont      = adjust_contrast(gray, CONTRAST)
equalized = histogram_equalization(gray)
hist_orig = compute_histogram(gray)
hist_eq   = compute_histogram(equalized)

# ── Gambar 1–5: Hasil konversi ───────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(15, 9))
fig.patch.set_facecolor('#111827')
fig.suptitle('Image Processing Results', color='white', fontsize=15, fontweight='bold', y=1.01)

images = [
    (original,  'RGB Original',                    True),
    (gray,      'Grayscale\n(Y=0.299R+0.587G+0.114B)', False),
    (binary,    f'Binary\n(Threshold = {THRESHOLD})',   False),
    (mbit,      f'M-bit Quantization\n({M_BIT}-bit, {2**M_BIT} level)', False),
    (bright,    f'Brightness\n(+{BRIGHTNESS})',          False),
    (cont,      f'Contrast\n(factor = {CONTRAST}×)',     False),
]

for ax, (img, title, is_rgb) in zip(axes.flat, images):
    ax.set_facecolor('#1f2937')
    if is_rgb:
        ax.imshow(img)
    else:
        ax.imshow(img, cmap='gray', vmin=0, vmax=255)
    ax.set_title(title, color='#e5e7eb', fontsize=11, fontweight='bold', pad=8)
    ax.axis('off')

plt.tight_layout()
plt.show()

# ── Gambar 6: Histogram Equalization ────────────────────────
fig2, axes2 = plt.subplots(1, 2, figsize=(12, 5))
fig2.patch.set_facecolor('#111827')
fig2.suptitle('Histogram Equalization', color='white', fontsize=14, fontweight='bold')

for ax in axes2:
    ax.set_facecolor('#1f2937')
    ax.tick_params(colors='#9ca3af', labelsize=8)
    for sp in ax.spines.values(): sp.set_edgecolor('#374151')

axes2[0].imshow(gray, cmap='gray', vmin=0, vmax=255)
axes2[0].set_title('Grayscale Original', color='#60a5fa', fontsize=12, fontweight='bold')
axes2[0].axis('off')

axes2[1].imshow(equalized, cmap='gray', vmin=0, vmax=255)
axes2[1].set_title('Histogram Equalization', color='#34d399', fontsize=12, fontweight='bold')
axes2[1].axis('off')

plt.tight_layout()
plt.show()

# ── Gambar 7: Grafik Histogram ───────────────────────────────
fig3, axes3 = plt.subplots(1, 2, figsize=(12, 4))
fig3.patch.set_facecolor('#111827')
fig3.suptitle('Histogram Grayscale', color='white', fontsize=14, fontweight='bold')

for ax in axes3:
    ax.set_facecolor('#1f2937')
    ax.tick_params(colors='#9ca3af', labelsize=8)
    for sp in ax.spines.values(): sp.set_edgecolor('#374151')

axes3[0].bar(range(256), hist_orig, color='#3b82f6', width=1, alpha=0.9)
axes3[0].set_title('Histogram Original', color='#60a5fa', fontsize=11, fontweight='bold')
axes3[0].set_xlabel('Intensitas (0–255)', color='#9ca3af', fontsize=9)
axes3[0].set_ylabel('Jumlah Pixel', color='#9ca3af', fontsize=9)

axes3[1].bar(range(256), hist_eq, color='#10b981', width=1, alpha=0.9)
axes3[1].set_title('Histogram Setelah Equalization', color='#34d399', fontsize=11, fontweight='bold')
axes3[1].set_xlabel('Intensitas (0–255)', color='#9ca3af', fontsize=9)
axes3[1].set_ylabel('Jumlah Pixel', color='#9ca3af', fontsize=9)

plt.tight_layout()
plt.show()

print("● Program Selesai")