# -*- coding: utf-8 -*-
"""UTS_Pengolahan_Citra_Digital.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNMOzY0iXnVR-Hl45mbG33b5CGFAfPSL
"""

# ============================================================
# UTS PENGOLAHAN CITRA DIGITAL
# Universitas Nahdlatul Ulama Sidoarjo
# ============================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image
import io

# ============================================================
# INPUT GAMBAR — Upload gambar di sini
# ============================================================

print("Silakan upload gambar (JPG atau PNG)...")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Baca sebagai grayscale
img_pil = Image.open(io.BytesIO(uploaded[filename])).convert('L')
F_uint8 = np.array(img_pil)

print(f"Gambar berhasil dimuat: {filename}")
print(f"Ukuran gambar: {F_uint8.shape[0]} x {F_uint8.shape[1]} piksel")

# ============================================================
# SOAL NO. 1 — Transformasi Intensitas: Negatif & Logaritmik
# ============================================================

F = F_uint8.astype(np.float64)

# Transformasi Negatif
G_negatif = (255 - F).astype(np.uint8)

# Transformasi Logaritmik
c = 255 / np.log(1 + np.max(F))
G_log = np.clip(c * np.log(1 + F), 0, 255).astype(np.uint8)

# Tampilkan hasil Soal 1
fig, axes = plt.subplots(2, 4, figsize=(18, 8))
fig.suptitle('Soal No. 1 - Transformasi Intensitas', fontsize=14, fontweight='bold')

axes[0, 0].imshow(F_uint8, cmap='gray')
axes[0, 0].set_title('Citra Asli (Original)')
axes[0, 0].axis('off')

axes[0, 1].hist(F_uint8.ravel(), 256, [0, 256], color='blue', alpha=0.7)
axes[0, 1].set_title('Histogram Asli')
axes[0, 1].set_xlabel('Nilai Piksel')
axes[0, 1].set_ylabel('Frekuensi')

axes[0, 2].imshow(G_negatif, cmap='gray')
axes[0, 2].set_title('Citra Negatif\n(G = 255 - F)')
axes[0, 2].axis('off')

axes[0, 3].hist(G_negatif.ravel(), 256, [0, 256], color='red', alpha=0.7)
axes[0, 3].set_title('Histogram Negatif')
axes[0, 3].set_xlabel('Nilai Piksel')
axes[0, 3].set_ylabel('Frekuensi')

axes[1, 0].imshow(G_log, cmap='gray')
axes[1, 0].set_title('Citra Logaritmik\n(G = c × log(1+F))')
axes[1, 0].axis('off')

axes[1, 1].hist(G_log.ravel(), 256, [0, 256], color='green', alpha=0.7)
axes[1, 1].set_title('Histogram Logaritmik')
axes[1, 1].set_xlabel('Nilai Piksel')
axes[1, 1].set_ylabel('Frekuensi')

axes[1, 2].axis('off')
axes[1, 3].axis('off')

plt.tight_layout()
plt.savefig('soal1_transformasi.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Soal 1 selesai! Gambar disimpan: soal1_transformasi.png")

# ============================================================
# SOAL NO. 2 — Konvolusi Filter: LPF, HPF, BPF
# ============================================================

# Kernel
kernel_lpf = np.ones((3, 3), np.float32) / 9
kernel_hpf = np.array([[-1,-1,-1],[-1, 8,-1],[-1,-1,-1]], dtype=np.float32)
kernel_bpf = np.array([[ 0,-1, 0],[-1, 5,-1],[ 0,-1, 0]], dtype=np.float32)

# Konvolusi
result_lpf = cv2.filter2D(F_uint8, -1, kernel_lpf)
result_hpf = np.clip(cv2.filter2D(F_uint8, cv2.CV_32F, kernel_hpf), 0, 255).astype(np.uint8)
result_bpf = np.clip(cv2.filter2D(F_uint8, cv2.CV_32F, kernel_bpf), 0, 255).astype(np.uint8)

# Statistik
print("\n📊 Rata-rata nilai piksel:")
print(f"  Asli  : {np.mean(F_uint8):.2f}")
print(f"  LPF   : {np.mean(result_lpf):.2f}")
print(f"  HPF   : {np.mean(result_hpf):.2f}")
print(f"  BPF   : {np.mean(result_bpf):.2f}")

# Tampilkan hasil Soal 2
fig, axes = plt.subplots(1, 4, figsize=(18, 5))
fig.suptitle('Soal No. 2 - Konvolusi Filter', fontsize=14, fontweight='bold')

data = [
    (F_uint8,    f'Original\nMean: {np.mean(F_uint8):.1f}'),
    (result_lpf, f'LPF – Blur\nMean: {np.mean(result_lpf):.1f}'),
    (result_hpf, f'HPF – Edge Detection\nMean: {np.mean(result_hpf):.1f}'),
    (result_bpf, f'BPF – Sharpening\nMean: {np.mean(result_bpf):.1f}'),
]

for ax, (im, title) in zip(axes, data):
    ax.imshow(im, cmap='gray')
    ax.set_title(title, fontsize=10)
    ax.axis('off')

plt.tight_layout()
plt.savefig('soal2_filter.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Soal 2 selesai! Gambar disimpan: soal2_filter.png")